'use client';

import { motion } from 'framer-motion';

const SOURCES = [
  {
    icon: '📊',
    title: 'HK Job Postings',
    detail: 'JobsDB, LinkedIn HK, jobs.gov.hk',
  },
  {
    icon: '🏛️',
    title: 'Regulatory Bodies',
    detail: 'HKMA, SFC, HKEX, HKICPA standards',
  },
  {
    icon: '📰',
    title: 'Industry Reports',
    detail: 'Salary surveys, market research, GBA trends',
  },
  {
    icon: '🤖',
    title: 'AI Analysis',
    detail: 'Web-search-enabled model with real-time data',
  },
];

export function DataSourcesChart() {
  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.2 }}
      className="bg-white rounded-xl border border-slate-200 p-6 shadow-sm"
    >
      <h3 className="text-lg font-semibold text-slate-900 mb-1">How we built your diagnosis</h3>
      <p className="text-sm text-slate-500 mb-5">
        Your assessment is generated by an AI model with live web search, cross-referencing these Hong Kong data sources:
      </p>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
        {SOURCES.map((s) => (
          <div key={s.title} className="bg-slate-50 rounded-lg p-4 text-center">
            <div className="text-2xl mb-2">{s.icon}</div>
            <div className="font-semibold text-slate-800 text-sm">{s.title}</div>
            <div className="text-xs text-slate-500 mt-1">{s.detail}</div>
          </div>
        ))}
      </div>

      <div className="bg-blue-50 border border-blue-100 rounded-lg p-4 text-sm text-blue-800">
        <strong>Note:</strong> Scores are AI-generated estimates informed by real market data, not exact measurements.
        The confidence range on your readiness score reflects this uncertainty.
      </div>
    </motion.div>
  );
}
